// Copyright 2023 hanmajid (Muhammad Farhan Majid)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import 'package:flutter/widgets.dart';

/// Class containing default Airtable icons.
///
/// This font was generated by FlutterIcon.com.
class AirtableIcons {
  /// No need for constructor. All properties are static.
  AirtableIcons._();

  /// Default Airtable icons family name.
  static const _kFontFam = 'AirtableIcons';

  /// Airtable icons package name.
  static const String? _kFontPkg = 'airtable_icons';

  /// Icon data for default 'android' glyph.
  static const IconData android =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'apple' glyph.
  static const IconData apple =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'apps' glyph.
  static const IconData apps =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'ascending' glyph.
  static const IconData ascending =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'attachment' glyph.
  static const IconData attachment =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'automations' glyph.
  static const IconData automations =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'autonumber' glyph.
  static const IconData autonumber =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'barcode' glyph.
  static const IconData barcode =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'bell' glyph.
  static const IconData bell =
      IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'bold' glyph.
  static const IconData bold =
      IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'bolt' glyph.
  static const IconData bolt =
      IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'book' glyph.
  static const IconData book =
      IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'calendar' glyph.
  static const IconData calendar =
      IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'caret' glyph.
  static const IconData caret =
      IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'chart' glyph.
  static const IconData chart =
      IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'chat' glyph.
  static const IconData chat =
      IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'check' glyph.
  static const IconData check =
      IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'checkboxUnchecked' glyph.
  static const IconData checkboxunchecked =
      IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'checklist' glyph.
  static const IconData checklist =
      IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'checkboxChecked' glyph.
  static const IconData checkboxchecked =
      IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'checkbox' glyph.
  static const IconData checkbox =
      IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'chevronDown' glyph.
  static const IconData chevrondown =
      IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'chevronLeft' glyph.
  static const IconData chevronleft =
      IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'clipboard' glyph.
  static const IconData clipboard =
      IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'chevronUp' glyph.
  static const IconData chevronup =
      IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'chevronRight' glyph.
  static const IconData chevronright =
      IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'code' glyph.
  static const IconData code =
      IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'cog' glyph.
  static const IconData cog =
      IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'collapse' glyph.
  static const IconData collapse =
      IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'collapseSidebar' glyph.
  static const IconData collapsesidebar =
      IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'count' glyph.
  static const IconData count =
      IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'count1' glyph.
  static const IconData count1 =
      IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'cube' glyph.
  static const IconData cube =
      IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'cursor' glyph.
  static const IconData cursor =
      IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'day' glyph.
  static const IconData day =
      IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'dayAuto' glyph.
  static const IconData dayauto =
      IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'dedent' glyph.
  static const IconData dedent =
      IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'descending' glyph.
  static const IconData descending =
      IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'dollar' glyph.
  static const IconData dollar =
      IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'down' glyph.
  static const IconData down =
      IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'download' glyph.
  static const IconData download =
      IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'dragHandle' glyph.
  static const IconData draghandle =
      IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'drive' glyph.
  static const IconData drive =
      IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'edit' glyph.
  static const IconData edit =
      IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'duplicate' glyph.
  static const IconData duplicate =
      IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'envelope' glyph.
  static const IconData envelope =
      IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'envelope1' glyph.
  static const IconData envelope1 =
      IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'expand1' glyph.
  static const IconData expand1 =
      IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'expand' glyph.
  static const IconData expand =
      IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'expandSidebar' glyph.
  static const IconData expandsidebar =
      IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'feed' glyph.
  static const IconData feed =
      IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'file' glyph.
  static const IconData file =
      IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'filter' glyph.
  static const IconData filter =
      IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'flag' glyph.
  static const IconData flag =
      IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'formula' glyph.
  static const IconData formula =
      IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'form' glyph.
  static const IconData form =
      IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'fullscreen' glyph.
  static const IconData fullscreen =
      IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'gallery' glyph.
  static const IconData gallery =
      IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'gantt' glyph.
  static const IconData gantt =
      IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'grid' glyph.
  static const IconData grid =
      IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'grid1' glyph.
  static const IconData grid1 =
      IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'group' glyph.
  static const IconData group =
      IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'gift' glyph.
  static const IconData gift =
      IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'help' glyph.
  static const IconData help =
      IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'heart' glyph.
  static const IconData heart =
      IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'hide1' glyph.
  static const IconData hide1 =
      IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'hide' glyph.
  static const IconData hide =
      IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'home' glyph.
  static const IconData home =
      IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'hyperlink' glyph.
  static const IconData hyperlink =
      IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'hyperlinkCancel' glyph.
  static const IconData hyperlinkcancel =
      IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'indent' glyph.
  static const IconData indent =
      IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'info' glyph.
  static const IconData info =
      IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'italic' glyph.
  static const IconData italic =
      IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'kanban' glyph.
  static const IconData kanban =
      IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'history' glyph.
  static const IconData history =
      IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'laptop' glyph.
  static const IconData laptop =
      IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'left' glyph.
  static const IconData left =
      IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'link' glyph.
  static const IconData link =
      IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'lightbulb' glyph.
  static const IconData lightbulb =
      IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'link1' glyph.
  static const IconData link1 =
      IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'lock' glyph.
  static const IconData lock =
      IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'logout' glyph.
  static const IconData logout =
      IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'lookup' glyph.
  static const IconData lookup =
      IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'markdown' glyph.
  static const IconData markdown =
      IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'menu' glyph.
  static const IconData menu =
      IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'mappin' glyph.
  static const IconData mappin =
      IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'multicollaborator' glyph.
  static const IconData multicollaborator =
      IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'mobile' glyph.
  static const IconData mobile =
      IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'minus' glyph.
  static const IconData minus =
      IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'multiselect' glyph.
  static const IconData multiselect =
      IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'number' glyph.
  static const IconData number =
      IconData(0xe85a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'overflow' glyph.
  static const IconData overflow =
      IconData(0xe85b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'ol' glyph.
  static const IconData ol =
      IconData(0xe85c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'paragraph' glyph.
  static const IconData paragraph =
      IconData(0xe85d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'paragraph1' glyph.
  static const IconData paragraph1 =
      IconData(0xe85e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'percent' glyph.
  static const IconData percent =
      IconData(0xe85f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'pause' glyph.
  static const IconData pause =
      IconData(0xe860, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'personalAuto' glyph.
  static const IconData personalauto =
      IconData(0xe861, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'pivot' glyph.
  static const IconData pivot =
      IconData(0xe862, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'phone' glyph.
  static const IconData phone =
      IconData(0xe863, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'play' glyph.
  static const IconData play =
      IconData(0xe864, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'plusFilled' glyph.
  static const IconData plusfilled =
      IconData(0xe865, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'print' glyph.
  static const IconData print =
      IconData(0xe866, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'quote' glyph.
  static const IconData quote =
      IconData(0xe867, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'public' glyph.
  static const IconData public =
      IconData(0xe868, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'plus' glyph.
  static const IconData plus =
      IconData(0xe869, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'premium' glyph.
  static const IconData premium =
      IconData(0xe86a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'radio' glyph.
  static const IconData radio =
      IconData(0xe86b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'publish' glyph.
  static const IconData publish =
      IconData(0xe86c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'paint' glyph.
  static const IconData paint =
      IconData(0xe86d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'redo' glyph.
  static const IconData redo =
      IconData(0xe86e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'redo1' glyph.
  static const IconData redo1 =
      IconData(0xe86f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'radioSelected' glyph.
  static const IconData radioselected =
      IconData(0xe870, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'personal' glyph.
  static const IconData personal =
      IconData(0xe871, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'richText' glyph.
  static const IconData richtext =
      IconData(0xe872, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'right' glyph.
  static const IconData right =
      IconData(0xe873, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'rollup' glyph.
  static const IconData rollup =
      IconData(0xe874, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'rollup1' glyph.
  static const IconData rollup1 =
      IconData(0xe875, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'rowHeightExtraLarge' glyph.
  static const IconData rowheightextralarge =
      IconData(0xe876, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'rowHeightLarge' glyph.
  static const IconData rowheightlarge =
      IconData(0xe877, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'rowHeightMedium' glyph.
  static const IconData rowheightmedium =
      IconData(0xe878, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'rowHeightSmall' glyph.
  static const IconData rowheightsmall =
      IconData(0xe879, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'search' glyph.
  static const IconData search =
      IconData(0xe87a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'selectCaret' glyph.
  static const IconData selectcaret =
      IconData(0xe87b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'select' glyph.
  static const IconData select =
      IconData(0xe87c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'shapes' glyph.
  static const IconData shapes =
      IconData(0xe87d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'share' glyph.
  static const IconData share =
      IconData(0xe87e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'settings' glyph.
  static const IconData settings =
      IconData(0xe87f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'smiley' glyph.
  static const IconData smiley =
      IconData(0xe880, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'slack' glyph.
  static const IconData slack =
      IconData(0xe881, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'sort' glyph.
  static const IconData sort =
      IconData(0xe882, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'show1' glyph.
  static const IconData show1 =
      IconData(0xe883, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'share1' glyph.
  static const IconData share1 =
      IconData(0xe884, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'show' glyph.
  static const IconData show =
      IconData(0xe885, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'stack' glyph.
  static const IconData stack =
      IconData(0xe886, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'star' glyph.
  static const IconData star =
      IconData(0xe887, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'strikethrough' glyph.
  static const IconData strikethrough =
      IconData(0xe888, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'switcher' glyph.
  static const IconData switcher =
      IconData(0xe889, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'tabs' glyph.
  static const IconData tabs =
      IconData(0xe88a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'team' glyph.
  static const IconData team =
      IconData(0xe88b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'teamLocked' glyph.
  static const IconData teamlocked =
      IconData(0xe88c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'text' glyph.
  static const IconData text =
      IconData(0xe88d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'thumbsUp' glyph.
  static const IconData thumbsup =
      IconData(0xe88e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'time' glyph.
  static const IconData time =
      IconData(0xe88f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'toggle' glyph.
  static const IconData toggle =
      IconData(0xe890, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'trash' glyph.
  static const IconData trash =
      IconData(0xe891, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'twitter' glyph.
  static const IconData twitter =
      IconData(0xe892, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'ul' glyph.
  static const IconData ul =
      IconData(0xe893, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'underline' glyph.
  static const IconData underline =
      IconData(0xe894, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'undo' glyph.
  static const IconData undo =
      IconData(0xe895, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'up' glyph.
  static const IconData up =
      IconData(0xe896, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'upload' glyph.
  static const IconData upload =
      IconData(0xe897, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'video' glyph.
  static const IconData video =
      IconData(0xe898, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'view' glyph.
  static const IconData view =
      IconData(0xe899, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'warning' glyph.
  static const IconData warning =
      IconData(0xe89a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'windows' glyph.
  static const IconData windows =
      IconData(0xe89b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for default 'x' glyph.
  static const IconData x =
      IconData(0xe89c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
